### ISSUE TITLE
Add more generalized support for `superclass` property

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#263]
We want to make it so that when this property is set in `provenance_schema.yaml` we no longer have to list all of the properties of the class this is inheriting.

For example in the current implementation of `Publication`, the property `superclass` is set to "Dataset". However, we still have to list all properties of `Dataset` as well as the new properties explicit for Publication

**Comment by libpitt** [comment]
Should have been addressed here: https://github.com/sennetconsortium/entity-api/issues/113

Can retest and remove later added duplicate properties in the `provenance_schema` when approved for working as expected.

**Comment by libpitt** [comment]
@maxsibilla Can confirm that the properties of the superclass are being populated. 

![Publication-registration](https://github.com/sennetconsortium/entity-api/assets/115558393/f0a7a415-216c-4225-9391-a3521391af76)

We would need to add another thing to support registration. And that is to either add `Publication` as a valid descendant in 

```
def build_all_dataset_constraints(entity):
    # Dataset ---> Dataset
    ancestor = build_constraint_unit(entity)
    descendant = build_constraint_unit(entity)
    descendant2 = build_constraint_unit(Ontology.ops().entities().PUBLICATION)
    return [
        build_constraint(ancestor, [descendant,  descendant2])
    ]


### Supporting code for ubkg within libs.Ontology:
    @staticmethod
    def modify_entities_cache():
        cache = current_app.ubkg.get_cache()
        entities = current_app.ubkg.entities
        key = f"VALUESET_{entities}"
        if key in cache:
            for e in cache[key]:
                if e['term'] == 'Publication Entity':
                    e['term'] = 'Publication'


with app.app_context():
   init_ontology()
   Ontology.modify_entities_cache()
```

### OR

Pass the name of the superclass `descendant_entity_type` as when calling:

`def validate_constraints_by_entities(ancestor, descendant, descendant_entity_type=None):`

**Comment by libpitt** [comment]
Also working is:
![shared_properties](https://github.com/sennetconsortium/entity-api/assets/115558393/66012ed8-97ee-4415-86d3-a1f4bb0c0f17)

The functionality is recursive so if were in the future set Dataset's superclass as `Entity` and defined a section for `Entity` with common properties, we'll end up with not only the properties of `Dataset`, for a given `Publication`, but the properties of all superclasses.

Constraint given in the meeting is:
A `Dataset` can be an ancestor of a `Publication`

Which is the same as:
A `Publication` can be descendant of a `Dataset`.

So instead of passing the superclass `Dataset` as `descendant_entity_type`, added it to:
```
def build_all_dataset_constraints(entity):
    # Dataset, Publication ---> Dataset
    ancestor = build_constraint_unit(entity)
    descendant = build_constraint_unit(entity)
    descendant2 = build_constraint_unit(Ontology.ops().entities().PUBLICATION)
    return [
        build_constraint(ancestor, [descendant,  descendant2])
    ]
```
